server.port=8081
spring.application.name=Banking-System
spring.datasource.url=jdbc:postgresql://localhost:5432/BankSystem
spring.datasource.username=postgres
spring.datasource.password=Crunches02
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.root=DEBUG


# Applying the necessary spring boot mail configuration.

#This username is basically the emailAddress you want Sender of your emails to
#Gmail automatically generates a password for this kind of app.

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gloryanwana4@gmail.com
spring.mail.password=qwxbtrgztbcbqqqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


glory-jwt.security=1d0f5b8a6e9af4bbdb1dbb2f9c1c5c5f2c5e3a6b8a86e7f7d8e9a6c5b8b2e3f1
glory-jwt.expiration=86400000


