server.port=8080
spring.application.name=Banking-System
spring.datasource.url=jdbc:postgresql://localhost:5432/BankSystem
spring.datasource.username=postgres
spring.datasource.password=Crunches02
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.root=DEBUG


# Applying the necessary configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#This username is basically the emailAddress you want Sender of your emails to
spring.mail.username=gloryanwana4@gmail.com
#Gmail automatically generates a password for this kind of app.
spring.mail.password=yyha febc yqbc hfdu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

